service: node-serverless-app

provider: 
  name: aws 
  runtime: nodejs10.x
  stage: ${env:STAGE}
  region: eu-central-1 
  environment:
    MONDAY_TOKEN: ${env:MONDAY_TOKEN}

functions: 
  app: 
    handler: app.handler 
    events: 
      - http: 
          path: /monday/newPulse 
          method: post
      - http: 
          path: /monday/createPulse
          method: post 
      - http: 
          path: /monday/assignId
          method: post 
      - http: 
          path: /set_id_counter
          method: post 
      - http: 
          path: /get_id_counter
          method: get 
      - http: 
          path: /test
          method: get 

plugins:
  - serverless-offline
  - serverless-dotenv-plugin